### ISSUE TITLE
Faire un vrai doc d'utilisation de l'api

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#219]
Actuellement seul la doc de Swagger permet d'avoir un peu d'information sur l'api.

Il faudrait faire une vraie doc, soit via le Readme, soit via un outil comme Gitbook.

Expliquer chaque partie de l'api et sont fonctionnement interne

**Comment by VSerain** [comment]
Test @valerie-daoduy

**Comment by valerie-daoduy** [comment]
test réponse

---
Valérie DAO-DUY
Intrapreneure
Start-up d'Etat Data.subvention
Direction de la jeunesse, de l'éducation populaire et de la vie 
associative
***@***.*** - 06 13 90 25 95

_Droit à la déconnexion: les messages que je pourrais vous adresser en 
dehors de vos horaires de travail ne requièrent pas de réponse immédiate 
de votre part_

-------- Courriel original --------

  		OBJET:
  		Re: [betagouv/api-subventions-asso] Faire un vrai doc d'utilisation 
de l'api (Issue #219)

  		DATE:
  		06.05.2022 11:12

  		DE:
  		Victor Serain ***@***.***>

  		À:
  		betagouv/api-subventions-asso 
***@***.***>

Test @valerie-daoduy [1]

--
Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
You are receiving this because you were mentioned.Message ID: 
***@***.***>

Links:
------
[1] https://github.com/valerie-daoduy
[2] 
https://github.com/betagouv/api-subventions-asso/issues/219#issuecomment-1119414027
[3]
